export default [
    { "id": "y2j98763l56x", "name": "Atlassian", "link": "https://metastatuspage.com/api" },
    { "id": "208q92hckwws", "name": "Box", "link": "https://status.box.com/api" },
    { "id": "yh6f0r4529hb", "name": "Cloudflare", "link": "https://cloudflarestatus.com/api" },
    { "id": "1k6wzpspjf99", "name": "Datadog", "link": "https://status.datadoghq.com/api" },
    { "id": "s2k7tnzlhrpw", "name": "DigitalOcean", "link": "https://status.digitalocean.com/api" },
    { "id": "srhpyqt94yxb", "name": "Discord", "link": "https://discordstatus.com/api" },
    { "id": "t34htyd6jblf", "name": "Dropbox", "link": "https://status.dropbox.com/api" },
    { "id": "qrxf5mzbrsxw", "name": "Duo", "link": "https://status.duo.com/api" },
    { "id": "kctbh9vrtdwd", "name": "GitHub", "link": "https://www.githubstatus.com/api" },
    { "id": "kwzln7bn4hg8", "name": "GoToMeeting", "link": "https://status.gotomeeting.com/api" },
    { "id": "1m1j8k4rtldg", "name": "Intercom", "link": "https://www.intercomstatus.com/api" },
    { "id": "tv3rvsrmny3p", "name": "InVision", "link": "https://status.invisionapp.com" },
    { "id": "636574ls1dpd", "name": "Librato", "link": "https://status.librato.com/api" },
    { "id": "nwg5xmnm9d17", "name": "New Relic", "link": "https://status.newrelic.com/api" },
    { "id": "t05vdsszxwtq", "name": "Opsgenie", "link": "https://opsgenie.status.atlassian.com/api" },
    { "id": "33yy6hwxnwr3", "name": "PagerDuty", "link": "https://status.pagerduty.com/api" },
    { "id": "3tgl2vf85cht", "name": "SendGrid", "link": "https://status.sendgrid.com/api" },
    { "id": "202yx2sdrxr3", "name": "sendwithus", "link": "https://status.sendwithus.com/api" },
    { "id": "gpkpyklzq55q", "name": "Twilio", "link": "https://status.twilio.com/api" },
    { "id": "zjttvm6ql9lp", "name": "Twitter", "link": "https://api.twitterstat.us/api" },
    { "id": "750cwd148kqj", "name": "Wistia", "link": "https://status.wistia.com/api" },
    { "id": "3dqfq14ym6xk", "name": "xMatters", "link": "https://status.xmatters.com/api" },
    { "id": "14qjgk812kgk", "name": "Zoom", "link": "https://status.zoom.us/api" }
]