<template>
  <v-container fill-height fluid class="pa-0 blue darken-3">
    <v-container fill-height fluid class="pa-0 blue darken-4 rounded-br-pill">
      <v-container class="py-0">
        <v-row>
          <v-col cols="12" md="6">
            <h1 class="text-h4 text-center">
              What does Allert do?
            </h1>
            <p>
              Allert is a &quot;cloud alerting engine&quot;. This means that it provides two services:
            </p>
            <ol>
              <li>Generating alerts from data input (in various formats) using custom scripts.</li>
              <li>Maintaining a master set of active alerts and enabling clients to access this information.</li>
            </ol>
            <p>
              This means that a monitoring system no longer needs to concern itself with alerting logic.
              It also means that the alerting logic is no longer coupled to the monitoring system.
              As a result of this, both of these components can be independently tested.
            </p>

            <h1 class="text-h4 text-center">
              What does Allert not do?
            </h1>
            <p>
              Allert doesn't handle any kind of monitoring, and it doesn't natively handle user-friendly notifications when alerts are generated.
              This means that it's designed to act as a bridge between an existing monitoring system (such as Zabbix or Nagios) and notification system (such as Opsgenie or Pagerduty.)
            </p>
            <p>
              At present, Allert also does not encrypt any stored alerts. Although it doesn't make any record of the data submitted to it, the alerts generated from that data
              are stored in plain text. If a system needs to be GDPR-compliant, it must not expose any kind of personally identifiable information in the text or metadata of any alerts.
            </p>
          </v-col>
          <v-col cols="12" md="6">
            <h1 class="text-h4 text-center">
              Benefits
            </h1>

            <h2 class="text-h5">
              Unit-tested alerts
            </h2>
            <p>
              Because alerting logic is now decoupled from the monitoring system, it can now be tested independently.
              This allows you to make sure that the correct alerts are generated by supplying test data, without needing to trigger undesirable behaviour in the live service or application.
            </p>

            <h2 class="text-h5">
              Complex alerting logic
            </h2>
            <p>
              Many monitoring systems will use a custom scripting language, or only allow you to provide hardcoded &quot;limits&quot; such as Very Low, Low, High and Very High. It also isn't
              always possible to generate alerts based upon a number of different data points.
              This can cause some friction - anyone maintaining the system needs to learn the new language, perform manual checks on the data, or feed it into a third-party system which provides those capabilities.
            </p>
            <p>
              By contrast, Allert alert definitions are standard C#, VB.NET or F# code snippets.
            </p>

            <h2 class="text-h5">
              Consolidated alerts
            </h2>
            <p>
              Some companies have multiple monitoring systems. These systems will typically have their own notification systems, which rarely communicate.
            </p>
            <p>
              If these monitoring systems push their data into Allert, they can form a single, central list of alerts for users of each of these monitoring systems to check when investigating issues.
            </p>

            <h2 class="text-h5">
              Cloud-ready alerting
            </h2>
            <p>
              A typical monitoring system will perform polling of various data points which can only be accessed internally. However, this model is increasingly poorly-suited as various
              services are moved to the cloud. A payment provider might provide webhooks in real time to indicate that a payment has failed, but accessing that data through polling an API can be difficult -
              not all of the data may be available, API requests could be rate limited, and so on.
            </p>
            <p>
              At an architectural level, few monitoring systems are equipped to receive web hooks or other real-time notifications. Allert can fill this gap; if the source system is configured to send web hook
              notifications to Allert, alert definitions can be run when these events occur.
            </p>

            <div class="link-container text-right">
              <v-btn text nuxt to="/roadmap">
                {{ languageStrings.pages.about.buttons.roadmap }}
                <v-icon class="pl-1">
                  mdi-arrow-right-bold
                </v-icon>
              </v-btn>
            </div>
          </v-col>
        </v-row>
      </v-container>
    </v-container>
  </v-container>
</template>

<style>
  ol { margin-bottom: 16px; }
  p { text-align: justify; }

  .link-container { margin-right: -16px; }
</style>

<script>
export default {
  components: {
  },
  props: {
    languageStrings: {
      type: Object,
      required: true
    }
  },
  head () {
    return {
      title: this.languageStrings.pages.about.title
    }
  }
}
</script>
